version: '3'
services:
    goupang-shipment:
        container_name: goupang-shipment
        image: 262872842537.dkr.ecr.ap-northeast-2.amazonaws.com/goupang/shipment:latest
        restart: always
        network_mode: 'host'

    nginx:
        container_name: nginx
        image: nginx
        restart: always
        ports:
            - '80:80/tcp'
            - '443:443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        network_mode: 'host'
        environment:
            - TZ=Asia/Seoul
        depends_on:
            - goupang-shipment
