services:
    redis-master:
        image: redis:latest
        container_name: redis-master
        command: ['redis-server', '--appendonly', 'yes']
        ports:
            - '6379:6379'
        volumes:
            - redis-master-data:/data

    redis-slave:
        image: redis:latest
        container_name: redis-slave
        command: ['redis-server', '--slaveof', 'redis-master', '6379']
        ports:
            - '6380:6379'
        depends_on:
            - redis-master
        volumes:
            - redis-slave-data:/data

    goupang-auth:
        container_name: goupang-auth
        image: 262872842537.dkr.ecr.ap-northeast-2.amazonaws.com/goupang/auth:latest
        restart: always
        ports:
            - '8000:8000'
        networks:
            - net
        depends_on:
            - master-node
            - slave-node1
            - slave-node2

    nginx:
        container_name: nginx
        image: nginx
        restart: always
        ports:
            - '80:80/tcp'
            - '443:443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - net
        environment:
            - TZ=Asia/Seoul
        depends_on:
            - goupang-auth

volumes:
    redis-master-data:
    redis-slave-data:

networks:
    net:
        driver: bridge
