services:
    goupang-auth:
        container_name: goupang-auth
        image: 262872842537.dkr.ecr.ap-northeast-2.amazonaws.com/goupang/auth:latest
        restart: always
        ports:
            - '8000:8000'
        networks:
            - net
        depends_on:
            - master-node
            - slave-node1
            - slave-node2

    nginx:
        container_name: nginx
        image: nginx
        restart: always
        ports:
            - '80:80/tcp'
            - '443:443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - net
        environment:
            - TZ=Asia/Seoul
        depends_on:
            - goupang-auth

volumes:
    redis-master-data:
    redis-slave-data:

networks:
    net:
        driver: bridge
