services:
    goupang-product:
        container_name: goupang-product
        image: 262872842537.dkr.ecr.ap-northeast-2.amazonaws.com/goupang/product:latest
        restart: always
        ports:
            - '8000:8000'
        networks:
            - net

    nginx:
        container_name: nginx
        image: nginx
        restart: always
        ports:
            - '80:80/tcp'
            - '443:443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - net
        environment:
            - TZ=Asia/Seoul
        depends_on:
            - goupang-product

networks:
    net:
        driver: bridge
